function A = importfile_user_eq_score(filename, startRow, endRow,outputtype)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   USERSCORESEQONLY = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   USERSCORESEQONLY = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   userscoreseqonly = importfile('user_scores_eq_only.txt', 2, 112470);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/03/02 16:33:25
%% check database versions
fileversion = '';
if isempty(strfind(filename,'20151020')) == 0
    fileversion = '20151020';
end
if isempty(strfind(filename,'20160224')) == 0
    fileversion = '20160224';
end
%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end
if nargin <=3
   outputtype = 'table'; 
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,14,16]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,3,4,5,6,7,8,9,10,11,14,16]);
rawCellColumns = raw(:, [12,13,15]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
switch outputtype
    case 'table'
        switch fileversion
            case {'20160224','20151020'}
                A = table;
                A.id = cell2mat(rawNumericColumns(:, 1));
                A.user_id = cell2mat(rawNumericColumns(:, 2));
                A.device_id = cell2mat(rawNumericColumns(:, 3));
                A.game_id = cell2mat(rawNumericColumns(:, 4));
                A.score = cell2mat(rawNumericColumns(:, 5));
                A.reaction_time = cell2mat(rawNumericColumns(:, 6));
                A.accuracy = cell2mat(rawNumericColumns(:, 7));
                A.played_at_utc = cell2mat(rawNumericColumns(:, 8));
        %         A.created_at_utc = cell2mat(rawNumericColumns(:, 9));
        %         A.game_id2 = cell2mat(rawNumericColumns(:, 10));
        %         A.friendly_id = cell2mat(rawNumericColumns(:, 11));
        %         A.name = rawCellColumns(:, 1);
        %         A.area = rawCellColumns(:, 2);
        %         A.sub_area_id = cell2mat(rawNumericColumns(:, 12));
        %         A.asset_prefix = rawCellColumns(:, 3);
        %         A.is_eq = cell2mat(rawNumericColumns(:, 13));

        end
    case 'array'
        switch fileversion
            case {'20160224','20151020'}
                nRow = size(rawNumericColumns,1);
                A = zeros(nRow,8);
                A(:,1) = cell2mat(rawNumericColumns(:, 1));
                A(:,2) = cell2mat(rawNumericColumns(:, 2));
                A(:,3) = cell2mat(rawNumericColumns(:, 3));
                A(:,4) = cell2mat(rawNumericColumns(:, 4));
                A(:,5) = cell2mat(rawNumericColumns(:, 5));
                A(:,6) = cell2mat(rawNumericColumns(:, 6));
                A(:,7) = cell2mat(rawNumericColumns(:, 7));
                A(:,8) = cell2mat(rawNumericColumns(:, 8));
        %         A.created_at_utc = cell2mat(rawNumericColumns(:, 9));
        %         A.game_id2 = cell2mat(rawNumericColumns(:, 10));
        %         A.friendly_id = cell2mat(rawNumericColumns(:, 11));
        %         A.name = rawCellColumns(:, 1);
        %         A.area = rawCellColumns(:, 2);
        %         A.sub_area_id = cell2mat(rawNumericColumns(:, 12));
        %         A.asset_prefix = rawCellColumns(:, 3);
        %         A.is_eq = cell2mat(rawNumericColumns(:, 13));

        end
end
